server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    click:
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://lcoalhost:8123/default
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
  elasticsearch:
    rest:
      uris: http://lcoalhost:9200
mybatis:
  type-aliases-package: com.zc.clickhouse.entity
  mapper-locations: classpath:/mapper/*.xml
