server:
  port: 9001

spring:
  application:
    name: seata-account-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false

mybatis-plus:
  type-aliases-package: com.zc.account.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
seata:
  tx-service-group: spang_tx_group
