server:
  port: 9002

spring:
  application:
    name: seata-order-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf8&useSSL=false



mybatis-plus:
  type-aliases-package: com.zc.order.entity
  configuration:
    map-underscore-to-camel-case: true
seata:
  tx-service-group: spang_tx_group
